apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdp
  namespace: cdp

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    application: kube-admin-pod
    version: v0.1
  name: kube-admin-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-admin-pod
  template:
    metadata:
      labels:
        application: kube-admin-pod
      annotations:
    spec:
      serviceAccountName: cdp
      containers:
      - name: kube-admin-pod
        image: "{{{IMAGE}}}"
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 300Mi 
